# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: YI's Blog
subtitle: 让我看看这堆数据里有什么...
author: YI
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://snorlaxa.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: YI的博客 | YI's Blog
header-img: img/home-bg.jpg
email: snorlaxa@163.com
description: "让我看看这堆数据里有什么..."
keyword: "数据开发,数据仓库,大数据"


# SNS settings
# RSS: false
weibo_username:
zhihu_username:
github_username:    snorlaxa
twitter_username:
facebook_username:
linkedin_username:

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username:

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing

souhucs_username: yzy

# Analytics settings
# Baidu Analytics
ba_track_id: 3701692d59c36342d12c77d9c4f8cf85
# Google Analytics
ga_track_id: ''            # Format: UA-xxxxxx-xx
ga_domain: 


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "抱歉让你看到了菜鸡，我这就走"
sidebar-avatar: img/karbe.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
#    {
#        title: "Yzy's Blog",
#        href: "http://blog.kaijun.rocks"
#    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: i_dont_wanna_use_default_archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Snorlaxa/Snorlaxa.github.io
  branch: hexo

souhucs:
    appid: cyvBC61mk
    conf: prod_6585689ae4d1e909fa52d3ecda7f631d